#!/bin/sh

NAME='mapchecrm_django'
DJANGODIR=/webapps/mapchi/environment_3_8_2/mapchecrm_django
SOCKFILE=/webapps/mapchi/environment_3_8_2/run/gunicorn.sock
USER=mapchiuser
GROUP=webapps
NUM_WORKERS=3
DJANGO_SETTINGS_MODULE=mapchecrm_django.settingsprod
DJANGO_WSGI_MODULE=mapchecrm_django.wsgi
TIMEOUT=120

cd $DJANGODIR
source ../environment_3_8_2/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--timeout $TIMEOUT \
--user=$USER --group=$GROUP \
--bind=unix:$SOCKFILE \
--log-level=debug \
--log-file=-
